<?php

declare(strict_types=1);

/*
 * The importmap of reference/config/importmap.rb, entry for entry and in the same order (the
 * pin_all_from directories expanded the way importmap-rails expands them), so module specifiers
 * are Rails' own: stimulus-loading's eagerLoadControllersFrom() reads controller names from these keys.
 * Paths are AssetMapper logical paths (see config/packages/asset_mapper.yaml). Rendered by
 * App\Twig\AssetExtension::javascriptImportmapTags(), which preloads every entry like Rails.
 */

return [
    'application' => ['path' => 'application.js', 'entrypoint' => true],
    '@hotwired/stimulus' => ['path' => 'stimulus.min.js'],
    '@hotwired/stimulus-loading' => ['path' => 'stimulus-loading.js'],
    '@hotwired/turbo-rails' => ['path' => 'turbo.js'],
    '@rails/actioncable' => ['path' => 'actioncable.esm.js'],
    '@rails/request.js' => ['path' => '@rails--request.js'],
    'lexxy' => ['path' => 'lexxy.js'],
    'highlight.js' => ['path' => 'highlight.js/core.js'],
    'initializers/autocomplete' => ['path' => 'initializers/autocomplete.js'],
    'initializers/current' => ['path' => 'initializers/current.js'],
    'initializers/highlight' => ['path' => 'initializers/highlight.js'],
    'initializers' => ['path' => 'initializers/index.js'],
    'initializers/rich_text' => ['path' => 'initializers/rich_text.js'],
    'lib/autocomplete/autocomplete_handler' => ['path' => 'lib/autocomplete/autocomplete_handler.js'],
    'lib/autocomplete/base_autocomplete_handler' => ['path' => 'lib/autocomplete/base_autocomplete_handler.js'],
    'lib/autocomplete/collection' => ['path' => 'lib/autocomplete/collection.js'],
    'lib/autocomplete/constants' => ['path' => 'lib/autocomplete/constants.js'],
    'lib/autocomplete/custom_elements/suggestion_option' => ['path' => 'lib/autocomplete/custom_elements/suggestion_option.js'],
    'lib/autocomplete/custom_elements/suggestion_select' => ['path' => 'lib/autocomplete/custom_elements/suggestion_select.js'],
    'lib/autocomplete/helpers' => ['path' => 'lib/autocomplete/helpers.js'],
    'lib/autocomplete/renderer' => ['path' => 'lib/autocomplete/renderer.js'],
    'lib/autocomplete/selection' => ['path' => 'lib/autocomplete/selection.js'],
    'lib/autocomplete/suggestion_context' => ['path' => 'lib/autocomplete/suggestion_context.js'],
    'lib/autocomplete/suggestion_controller' => ['path' => 'lib/autocomplete/suggestion_controller.js'],
    'lib/autocomplete/suggestion_results_controller' => ['path' => 'lib/autocomplete/suggestion_results_controller.js'],
    'lib/autocomplete/utils' => ['path' => 'lib/autocomplete/utils.js'],
    'lib/cookie' => ['path' => 'lib/cookie.js'],
    'lib/rich_text/campfire_extension' => ['path' => 'lib/rich_text/campfire_extension.js'],
    'lib/rich_text/cite_node' => ['path' => 'lib/rich_text/cite_node.js'],
    'controllers/application' => ['path' => 'controllers/application.js'],
    'controllers/auto_submit_controller' => ['path' => 'controllers/auto_submit_controller.js'],
    'controllers/autocomplete_controller' => ['path' => 'controllers/autocomplete_controller.js'],
    'controllers/badge_dot_controller' => ['path' => 'controllers/badge_dot_controller.js'],
    'controllers/boost_delete_controller' => ['path' => 'controllers/boost_delete_controller.js'],
    'controllers/composer_controller' => ['path' => 'controllers/composer_controller.js'],
    'controllers/copy_to_clipboard_controller' => ['path' => 'controllers/copy_to_clipboard_controller.js'],
    'controllers/drop_target_controller' => ['path' => 'controllers/drop_target_controller.js'],
    'controllers/element_removal_controller' => ['path' => 'controllers/element_removal_controller.js'],
    'controllers/filter_controller' => ['path' => 'controllers/filter_controller.js'],
    'controllers/form_controller' => ['path' => 'controllers/form_controller.js'],
    'controllers' => ['path' => 'controllers/index.js'],
    'controllers/lightbox_controller' => ['path' => 'controllers/lightbox_controller.js'],
    'controllers/local_time_controller' => ['path' => 'controllers/local_time_controller.js'],
    'controllers/maintain_scroll_controller' => ['path' => 'controllers/maintain_scroll_controller.js'],
    'controllers/messages_controller' => ['path' => 'controllers/messages_controller.js'],
    'controllers/notifications_controller' => ['path' => 'controllers/notifications_controller.js'],
    'controllers/popup_controller' => ['path' => 'controllers/popup_controller.js'],
    'controllers/presence_controller' => ['path' => 'controllers/presence_controller.js'],
    'controllers/pwa_install_controller' => ['path' => 'controllers/pwa_install_controller.js'],
    'controllers/read_rooms_controller' => ['path' => 'controllers/read_rooms_controller.js'],
    'controllers/refresh_room_controller' => ['path' => 'controllers/refresh_room_controller.js'],
    'controllers/reply_controller' => ['path' => 'controllers/reply_controller.js'],
    'controllers/rooms_list_controller' => ['path' => 'controllers/rooms_list_controller.js'],
    'controllers/scroll_into_view_controller' => ['path' => 'controllers/scroll_into_view_controller.js'],
    'controllers/search_results_controller' => ['path' => 'controllers/search_results_controller.js'],
    'controllers/sessions_controller' => ['path' => 'controllers/sessions_controller.js'],
    'controllers/soft_keyboard_controller' => ['path' => 'controllers/soft_keyboard_controller.js'],
    'controllers/sorted_list_controller' => ['path' => 'controllers/sorted_list_controller.js'],
    'controllers/sound_controller' => ['path' => 'controllers/sound_controller.js'],
    'controllers/toggle_class_controller' => ['path' => 'controllers/toggle_class_controller.js'],
    'controllers/turbo_frame_controller' => ['path' => 'controllers/turbo_frame_controller.js'],
    'controllers/turbo_streaming_controller' => ['path' => 'controllers/turbo_streaming_controller.js'],
    'controllers/typing_notifications_controller' => ['path' => 'controllers/typing_notifications_controller.js'],
    'controllers/unfurl_controller' => ['path' => 'controllers/unfurl_controller.js'],
    'controllers/upload_preview_controller' => ['path' => 'controllers/upload_preview_controller.js'],
    'controllers/web_share_controller' => ['path' => 'controllers/web_share_controller.js'],
    'helpers/dom_helpers' => ['path' => 'helpers/dom_helpers.js'],
    'helpers/navigator_helpers' => ['path' => 'helpers/navigator_helpers.js'],
    'helpers/string_helpers' => ['path' => 'helpers/string_helpers.js'],
    'helpers/timing_helpers' => ['path' => 'helpers/timing_helpers.js'],
    'helpers/turbo_helpers' => ['path' => 'helpers/turbo_helpers.js'],
    'models/client_message' => ['path' => 'models/client_message.js'],
    'models/file_uploader' => ['path' => 'models/file_uploader.js'],
    'models/message_formatter' => ['path' => 'models/message_formatter.js'],
    'models/message_paginator' => ['path' => 'models/message_paginator.js'],
    'models/scroll_manager' => ['path' => 'models/scroll_manager.js'],
    'models/typing_tracker' => ['path' => 'models/typing_tracker.js'],
    'languages/bash' => ['path' => 'languages/bash.js'],
    'languages/css' => ['path' => 'languages/css.js'],
    'languages/diff' => ['path' => 'languages/diff.js'],
    'languages/go' => ['path' => 'languages/go.js'],
    'languages/java' => ['path' => 'languages/java.js'],
    'languages/javascript' => ['path' => 'languages/javascript.js'],
    'languages/json' => ['path' => 'languages/json.js'],
    'languages/python' => ['path' => 'languages/python.js'],
    'languages/ruby' => ['path' => 'languages/ruby.js'],
    'languages/rust' => ['path' => 'languages/rust.js'],
    'languages/sql' => ['path' => 'languages/sql.js'],
    'languages/xml' => ['path' => 'languages/xml.js'],
];
