# Generates tests/fixtures/richtext/canonical.json: for every body in corpus.json (the Rust port's
# rich text corpus, generated by its reference-tools/richtext/generate.rb), what Action Text stores
# when the body is assigned (ActionText::Content.dump(body), i.e. Content.new(body).to_html) and
# what Content#to_s renders (the json view's `message.body.to_s`).
#
# Run inside the reference image (see tests/fixtures/richtext/run.sh).
require "json"

INPUT = ENV.fetch("CORPUS", "/corpus/corpus.json")
OUTPUT = ENV.fetch("OUTPUT", "/corpus/canonical.json")

Rails.logger = Logger.new(nil)
ActiveRecord::Base.logger = nil

def outcome
  { "ok" => yield }
rescue Exception => e
  { "error" => e.class.name, "message" => e.message.to_s.scrub[0, 300] }
end

TIME = Time.utc(2024, 1, 2, 3, 4, 5)

def create_user(key, name, bio: nil)
  User.insert!({ name: name, email_address: "#{key}@example.com", password_digest: BCrypt::Password.create("secret123456", cost: 4),
    bio: bio, role: 0, status: 0, created_at: TIME, updated_at: TIME })
  User.find_by!(email_address: "#{key}@example.com")
end

create_user("david", "David", bio: "Founder")
create_user("jason", "Jason")
create_user("kevin", "Kevin", bio: "Ops")
create_user("mallory", "Mallory <b>&amp;</b> \"Evil\"", bio: "<script>alert(1)</script>")
create_user("obrien", "Seán O'Brien 🎉")
create_user("deleted", "Deleted").delete
Room.insert!({ name: "Pets", type: "Rooms::Open", creator_id: 1, created_at: TIME, updated_at: TIME })

corpus = JSON.parse(File.read(INPUT))

def with_request(host)
  request = ActionDispatch::Request.new(Rack::MockRequest.env_for("http://#{host}/"))
  controller = MessagesController.new
  controller.set_request!(request)
  controller.set_response!(ActionDispatch::Response.new)
  Current.set(request: request) do
    ActionText::Content.with_renderer(controller) { yield controller.view_context }
  end
end

extra = [ "", "   ", "hello", "hello <b>world", "1 < 2 & 3 > 2", "line one\nline two", "<script>alert(1)</script>x",
  "  <p>padded</p>\n", "https://example.com/a?b=1&c=2", "😀", "<figure data-trix-attachment='{\"contentType\":\"image/png\",\"url\":\"https://example.com/a.png\"}'><img src=x></figure>" ]
bodies = corpus.fetch("cases").map { |c| [ c["name"], c["body"], c["host"] ] } +
  extra.each_with_index.map { |b, i| [ "extra #{i}", b, nil ] }

cases = bodies.map do |name, body, host|
  with_request(host || "once.campfire.test") do
    {
      "name" => name,
      "body" => body,
      "canonical" => outcome { ActionText::Content.new(body).to_html },
      "stored_twice" => outcome { ActionText::Content.new(ActionText::Content.new(body).to_html).to_html },
      "to_s" => outcome { ActionText::Content.new(body).to_s.to_s }
    }
  end
end

File.write(OUTPUT, JSON.pretty_generate({ "generated_by" => "tests/fixtures/richtext/generate_canonical.rb", "cases" => cases }) + "\n")
puts "Wrote #{cases.size} cases to #{OUTPUT}"
