<?php

declare(strict_types=1);

namespace App\Tests\Unit\Rails;

use App\Rails\KeyGenerator;

/**
 * The golden vectors generated by the reference Rails app (tests/vectors).
 */
final class Vectors
{
    /** @var array<string, array<string, mixed>> */
    private static array $files = [];

    /** @return array<string, mixed> */
    public static function load(string $file = 'rails_compat'): array
    {
        return self::$files[$file] ??= json_decode((string) file_get_contents(\dirname(__DIR__, 2).'/vectors/'.$file.'.json'), true, 512, \JSON_THROW_ON_ERROR);
    }

    public static function get(string $path, string $file = 'rails_compat'): mixed
    {
        $value = self::load($file);
        foreach (explode('.', $path) as $key) {
            $value = $value[$key];
        }

        return $value;
    }

    /**
     * Cases as data sets named after their "case" label (or index).
     *
     * @return iterable<string, array{array<string, mixed>}>
     */
    public static function cases(string $path, string $file = 'rails_compat'): iterable
    {
        foreach (self::get($path, $file) as $i => $case) {
            yield \sprintf('#%d %s', $i, \is_array($case) && \is_string($case['case'] ?? null) ? $case['case'] : '') => [$case];
        }
    }

    public static function keys(): KeyGenerator
    {
        static $keys;

        return $keys ??= new KeyGenerator(self::get('secret_key_base'));
    }

    public static function rotatedKeys(): KeyGenerator
    {
        return new KeyGenerator(self::get('rotated_secret_key_base'));
    }

    public static function time(?string $iso): ?\DateTimeImmutable
    {
        return null === $iso ? null : new \DateTimeImmutable($iso);
    }

    public static function now(): \DateTimeImmutable
    {
        return new \DateTimeImmutable(self::get('now'));
    }
}
