<?php

declare(strict_types=1);

namespace App\Tests\Unit\RichText;

use App\Rails\KeyGenerator;
use App\Rails\SignedGlobalId;
use App\RichText\Attachables\AttachableLocator;
use App\RichText\Attachables\MentionUser;
use App\RichText\Attachables\MentionUsers;
use App\RichText\RenderContext;
use App\RichText\Ruby;
use Symfony\Component\Clock\MockClock;

/**
 * The rich text corpus (tests/fixtures/richtext/corpus.json, the Rust port's
 * crates/richtext/tests/corpus/expected.json, generated by running Campfire's real Rails pipeline
 * on each body) and the records it was generated with.
 */
final class Corpus
{
    /** The parity SECRET_KEY_BASE the corpus SGIDs were signed with (tests/vectors/rails_compat.json). */
    public const string SECRET_KEY_BASE = '5335c3b1ad35b4ad170c3413bd651ef3b6ed64e257261871a6de3f978cf3868ee417a927040935fb30b0f7debdedb34a2a403e9f34b16cf594c917c2ecd4a995';

    /** @var array<string, mixed> */
    private static array $json;
    /** @var array<string, mixed> */
    private static array $canonical;

    /** @return array<string, mixed> */
    public static function json(): array
    {
        return self::$json ??= json_decode((string) file_get_contents(\dirname(__DIR__, 2).'/fixtures/richtext/corpus.json'), true, 512, \JSON_THROW_ON_ERROR);
    }

    /** @return array<string, mixed> */
    public static function canonical(): array
    {
        return self::$canonical ??= json_decode((string) file_get_contents(\dirname(__DIR__, 2).'/fixtures/richtext/canonical.json'), true, 512, \JSON_THROW_ON_ERROR);
    }

    public static function mentionUser(int $id): MentionUser
    {
        foreach (self::json()['users'] as $user) {
            if ($user['id'] === $id) {
                $avatar = '<a title="'.Ruby::h($user['title']).'" class="btn avatar" data-turbo-frame="_top" href="'.Ruby::h($user['user_path']).'">'
                    .'<img aria-hidden="true" src="'.Ruby::h($user['avatar_path']).'" width="48" height="48" /></a>';

                return new MentionUser($user['id'], $user['name'], $user['attachable_sgid'], $avatar);
            }
        }

        throw new \OutOfBoundsException((string) $id);
    }

    public static function context(?string $host = null): RenderContext
    {
        $users = [];
        foreach (self::json()['users'] as $user) {
            $users[$user['id']] = self::mentionUser($user['id']);
        }
        $lookup = new class($users) implements MentionUsers {
            /** @param array<int, MentionUser> $users */
            public function __construct(private array $users)
            {
            }

            public function find(int $id): ?MentionUser
            {
                return $this->users[$id] ?? null;
            }
        };
        $locator = new AttachableLocator(new SignedGlobalId(new KeyGenerator(self::SECRET_KEY_BASE)), $lookup, new MockClock('2024-01-02 03:04:05 UTC'));

        return new RenderContext($locator, $host ?? self::json()['request_host']);
    }

    /**
     * Rails' presentation as the port renders it on purpose: `<` and `>` are escaped in attribute
     * values, the links rails_autolink inserted inside an attribute value (its stored XSS) are
     * left as the text they replaced, and `name` attributes are dropped.
     */
    public static function withPortDivergences(string $rails): string
    {
        $inserted = '<a target="_blank" href="';
        $out = '';
        $state = 'text';
        $i = 0;
        $length = \strlen($rails);
        while ($i < $length) {
            if ('value' === $state && 0 === substr_compare($rails, $inserted, $i, \strlen($inserted))) {
                $textStart = strpos($rails, '">', $i) + 2;
                $textEnd = strpos($rails, '</a>', $textStart);
                $out .= str_replace('>', '&gt;', substr($rails, $textStart, $textEnd - $textStart));
                $i = $textEnd + 4;
                continue;
            }
            if ('tag' === $state && 0 === substr_compare($rails, ' name="', $i, 7)) {
                $i = strpos($rails, '"', $i + 7) + 1;
                continue;
            }
            $c = $rails[$i];
            $state = match (true) {
                'text' === $state && '<' === $c => 'tag',
                'tag' === $state && '>' === $c => 'text',
                'tag' === $state && '"' === $c => 'value',
                'value' === $state && '"' === $c => 'tag',
                default => $state,
            };
            $out .= 'value' === $state && '<' === $c ? '&lt;' : ('value' === $state && '>' === $c ? '&gt;' : $c);
            ++$i;
        }

        return $out;
    }
}
